version: 2.1

orbs:
    node: circleci/node@5.0.2

jobs:
    setup-and-build:
        docker:
            - image: node:lts
        working_directory: /app
        steps:
            - checkout
            - node/install-packages
            - run:
                  name: Build "test"
                  command: npm run build:test
            - store_artifacts:
                  path: /app/build/test.js

workflows:
    build:
        jobs:
            - setup-and-build
